all:
	echo "you code here..."

icmp-forge:
	gcc ICMP-forge.c -o ICMP-forge.out
	sudo ./ICMP-forge.out

arp-forge:
	gcc ARP-forge.c -o ARP-forge.out
	sudo ./ARP-forge.out

udp-forge:
	gcc UDP-forge.c -o UDP-forge.out
	sudo ./UDP-forge.out

clean:
	rm -rf *.out

