// Auto-generated by mcc. Do not modify.
	.file "input.txt"
	.text
mcc_format: .string "%d\n"
	.globl main
	.type main, @function
main:
	pushq   %rbp
	movq    %rsp, %rbp
	movq $5, %rax
	movq %rax, a(%rip)
	movq a(%rip), %rax
	push %rax
	movq $2, %rax
	push %rax
	movq $5, %rax
	pop %rbx
	imulq %rbx, %rax
	pop %rbx
	addq %rbx, %rax
	movq %rax, b(%rip)
	movq b(%rip), %rax
	movq %rax, %rsi
	leaq mcc_format(%rip), %rdi
	call printf
	popq    %rbp
	ret

	.data
	.global	a
	.align 8
	.type	a, @object
	.size	a, 8
a:
	.quad	0
	.global	b
	.align 8
	.type	b, @object
	.size	b, 8
b:
	.quad	0
// End and bye.

